Vagrant.configure("2") do |config|
  config.vm.box = "ol74"
  config.vm.box_url = "http://yum.oracle.com/boxes/oraclelinux/ol74/ol74.box"
  config.vm.box_check_update = false
  config.vm.provision "shell", path: "bootstrap.sh"
end
