Vagrant.configure("2") do |config|
  config.vm.box = "ol74"
  config.vm.box_url = "http://yum.oracle.com/boxes/oraclelinux/ol74/ol74.box"
  config.vm.box_check_update = false
  config.vm.network :forwarded_port, guest: 3690, host: 3690
  config.vm.network :forwarded_port, guest: 8080, host: 8080
  config.vm.network :forwarded_port, guest: 9000, host: 9000
  config.vm.provision "shell", path: "./jenkins/bootstrap.sh"
  config.vm.provision "shell", path: "./svn/bootstrap.sh"
  # config.vm.provision "shell", path: "./gogs/bootstrap.sh"
  config.vm.provider "virtualbox" do |v|
    v.name = "tool-box"
    v.memory = 1024
    v.cpus = 1
  end
end
