Vagrant.configure("2") do |config|
  config.vm.box = "ol74"
  config.vm.box_url = "http://yum.oracle.com/boxes/oraclelinux/ol74/ol74.box"
  config.vm.box_check_update = false
  # config.vm.network :forwarded_port, guest: 3690, host: 3690
  config.vm.provision "shell", path: "bootstrap.sh"
  # config.vm.provider "virtualbox" do |v|
  #   v.name = "subversion"
  #   v.memory = 512
  #   v.cpus = 1
  # end
end
