Vagrant.configure("2") do |config|
  config.vm.box = "ol7-latest"
  config.vm.box_url = "https://yum.oracle.com/boxes/oraclelinux/latest/ol7-latest.box"
  config.vm.box_check_update = false
  config.vm.provision "shell", path: "bootstrap.sh"
end
