Vagrant.configure("2") do |config|
  config.vm.box = "ol74"
  config.vm.box_url = "http://yum.oracle.com/boxes/oraclelinux/ol74/ol74.box"
  config.vm.network :forwarded_port, guest: 1521, host: 1521
  config.vm.network :forwarded_port, guest: 8080, host: 8080
  config.vm.provision "shell", path: "bootstrap.sh"
  config.vm.provider "virtualbox" do |v|
    v.name = "xedb"
    v.memory = 1024
    v.cpus = 1
  end
end